version: '3.8'
services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: emergency_centers
    volumes:
      - mongo_data:/data/db
  app:
    build: .
    container_name: emergency-centers-api
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/emergency_centers
volumes:
  mongo_data:
